export const setType = (type) => ({type: 'products/type', payload: type})
export const setPage = (page) => ({type: 'products/page', payload: page})
export const setSort = (sort) => ({type: 'products/sort', payload: sort})
export const setLayout = (layout) => ({type: 'products/layout', payload: layout})
export const addLiked = (code) => ({type: 'liked/add', payload: code})
export const reset = () => ({type: 'reset'})